routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/page/{slug?}', 'BlogController@page')->name('page');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');
Route::get('/blog/search', 'BlogController@search')->name('search');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/page', 'PageController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::get('/options', 'OptionsController@index')->name('admin.option.index');
    Route::get('/options/edit', 'OptionsController@edit')->name('admin.option.edit');

    Route::group(['prefix' => 'user_managment', 'namespace' => 'UserManagment'], function () {
        Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
        Route::resource('/role', 'RoleController', ['as' => 'admin.user_managment']);
    });


});

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    //
    protected $fillable = [
        'id', 'name'
    ];
    public function users()
    {
        //return $this->morphedByMany(User::class, 'user_role');
        return $this->belongsToMany(User::class, 'user_role');
    }
}

app/Http/Controllers/Admin/UserManagment/RoleController.php
<?php

namespace App\Http\Controllers\Admin\UserManagment;

use App\Http\Controllers\Controller;
use App\Role;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('admin.user_managment.roles.index', [
            'roles' => Role::orderBy('created_at', 'desc')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.user_managment.roles.create', [
            'role' => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $role = Role::create($request->all());
        return redirect()->route('admin.user_managment.role.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Role $role
     * @return Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Role $role
     * @return Response
     */
    public function edit(Role $role)
    {
        return view('admin.user_managment.roles.edit', [
            'role' => $role
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Role $role
     * @return Response
     */
    public function update(Request $request, Role $role)
    {
        $role->update($request->all());

        return redirect()->route('admin.user_managment.role.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Role $role
     * @return Response
     */
    public function destroy(Role $role)
    {
        $role->delete();
        return redirect()->route('admin.user_managment.role.index');
    }
}

app/Http/Controllers/Admin/UserManagment/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagment;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
        return view('admin.user_managment.users.index', [
            'users' => User::paginate(10),
            'roles' => Role::orderBy('created_at', 'desc')->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('admin.user_managment.users.create', [
            'user' => [],
            'roles' => Role::get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
        $user = User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password'])

        ]);
        if ($request->input('roles')):
            $user->categories()->attach($request->input('roles'));
        endif;
        return redirect()->route('admin.user_managment.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return Response
     */
    public function show(User $user)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Response
     */
    public function edit(User $user)
    {
        return view('admin.user_managment.users.edit', [
            'user' => $user,
            'roles' => Role::get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param User $user
     * @return Response
     */
    public function update(Request $request, User $user)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', Rule::unique('users')->ignore($user->id)],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
        ]);

        $user->name = $request['name'];
        $user->email = $request['email'];
        $request['password'] == null ?: $user->password = bcrypt($request['password']);
        $user->roles()->detach();
        if ($request->input('roles')):
            $user->roles()->attach($request->input('roles'));
        endif;
        $user->save();

        return redirect()->route('admin.user_managment.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return Response
     */
    public function destroy(User $user)
    {
        $user->roles()->detach();
        $user->delete();
        return redirect()->route('admin.user_managment.user.index');
    }
}

resources/views/admin/user_managment/roles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
            @slot('title') Создание роли @endslot
            @slot('parent') Главная @endslot
            @slot('active') Роль @endslot
        @endcomponent

        <hr/>

        <form class="form-horizontal" action="{{route('admin.user_managment.role.store')}}" method="post">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.user_managment.roles.partials.form')
        </form>
    </div>

@endsection

resources/views/admin/user_managment/roles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
            @slot('title') Редактирование роли @endslot
            @slot('parent') Главная @endslot
            @slot('active') Роль @endslot
        @endcomponent

        <hr/>

        <form class="form-horizontal" action="{{route('admin.user_managment.role.update', $role)}}" method="post">
            {{method_field('PUT')}}
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.user_managment.roles.partials.form')
        </form>
    </div>

@endsection

resources/views/admin/user_managment/roles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">

        @component('admin.components.breadcrumb')
            @slot('title') Список ролей @endslot
            @slot('parent') Главная @endslot
            @slot('active')  Пользователи @endslot
        @endcomponent


        <a href="{{route('admin.user_managment.role.create')}}" class="btn btn-primary pull-right my-4"><i
                    class="fa fa-plus-square-o "></i> Создать роль</a>

        <table class="table table-striped ">
            <thead>
            <th>Имя</th>
            <th class="text-right">Действие</th>
            </thead>
            <tbody>
            @forelse ($roles as $role)
                <tr>
                    <td>{{$role->name}}</td>

                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить?')){return true }else{return false}"
                              action="{{route('admin.user_managment.role.destroy', $role)}}" method="post">
                            {{method_field('DELETE')}}
                            {{csrf_field()}}
                            <a class="btn btn-default" href="{{route('admin.user_managment.role.edit', $role)}}"><i
                                        class="fa fa-edit"></i></a>
                            <button class="btn" type="submit"><i class="fa fa-trash-o"></i></button>
                        </form>


                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center"><h2>Данные отсутствуют</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <td colspan="5">
                <ul class="pagination pull-right">
                    {{$roles->links()}}
                </ul>
            </td>
            </tfoot>
        </table>
    </div>

@endsection