routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
Route::get('/blog/page/{slug?}', 'BlogController@page')->name('page');
Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');
Route::get('/blog/search', 'BlogController@search')->name('search');

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/category', 'CategoryController', ['as' => 'admin']);
    Route::resource('/page', 'PageController', ['as' => 'admin']);
    Route::resource('/article', 'ArticleController', ['as' => 'admin']);
    Route::get('/options', 'OptionsController@index')->name('admin.option.index');
    Route::get('/options/edit', 'OptionsController@edit')->name('admin.option.edit');

    Route::group(['prefix' => 'user_managment', 'namespace' => 'UserManagment'], function () {
        Route::resource('/user', 'UserController', ['as' => 'admin.user_managment']);
        Route::resource('/role', 'RoleController', ['as' => 'admin.user_managment']);
    });


});

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

app/Article.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Article extends Model
{

    // Mass assigned
    protected $fillable = ['title', 'slug', 'description_short', 'description', 'image', 'image_show', 'meta_title', 'meta_description', 'meta_keyword', 'published', 'viewed', 'created_by', 'modified_by'];

    // Mutators
    public function setSlugAttribute($value)
    {
        $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40) . "-" . Carbon::now()->format('dmyHi'), '-');
    }

    // Polymorphic relation with categories
    public function categories()
    {
        return $this->morphToMany('App\Category', 'categoryable');
    }

    public function scopeLastArticles($query, $count)
    {
        return $query->orderBy('created_at', 'desc')->take($count)->get();
    }


}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {

        if ($request->input('searching')):
            $article = Article::where('title', 'LIKE', '%' . $request->input('searching') . '%')->paginate(10);
        elseif ($request->input('category_search')):
            if (($request->input('category_search')) == 0):
                $article = Article::orderBy('created_at', 'desc')->paginate(10);
            else:
                $category = Category::where('id', $request->input('category_search'))->first();
                $article = $category->articles()->paginate(20);
            endif;
        elseif ($request->input('category_published')):
            if (($request->input('category_published')) == 1):
                $article = Article::orderBy('created_at', 'desc')->where('published', 1)->paginate(10);
            elseif (($request->input('category_published')) == 0):
                $article = Article::where('published', 0)->paginate(10);
            endif;
        else:
            $article = Article::orderBy('created_at', 'desc')->paginate(10);
        endif;

        return view('admin.articles.index', [
            'articles' => $article,
            'categories' => Category::orderBy('created_at', 'desc')->paginate(10)

        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        //
        return view('admin.articles.create', [
            'article' => [],
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''


        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
        $validator = $request->validate(
            ['title' => ['required', 'string', 'max:255'],
                'description_short' => ['required'],
                'description' => ['required'],

            ]
        );
        $article = Article::create($request->all());

        //Cat
        if ($request->input('categories')):
            $article->categories()->attach($request->input('categories'));
        endif;
        //img
        if ($request->hasFile('image')):
            $path = $request->image->store('uploads', 'public');
            $article->image = $path;
            $article->save();
        endif;
        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Article $article
     * @return Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Article $article
     * @return Response
     */
    public function edit(Article $article)
    {
        //
        return view('admin.articles.edit', [
            'article' => $article,
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter' => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Article $article
     * @return Response
     */
    public function update(Request $request, Article $article)
    {
        $validator = $request->validate(
            ['title' => ['required', 'string', 'max:255'],
                'slug' => ['required', 'string', 'max:255'],
                'description_short' => ['required'],
                'description' => ['required'],

            ]
        );
        if (($request->hasFile('image')) && ($article->image != null) && (file_exists(public_path() . '/storage/' . $article->image))):
            unlink(public_path('/storage/' . $article->image));
            $article->image = null;
        endif;
        $article->update($request->except('slug'));


        $article->categories()->detach();
        if ($request->input('categories')):
            $article->categories()->attach($request->input('categories'));
        endif;

        //Img
        if ($request->hasFile('image')):

            $path = $request->image->store('uploads', 'public');
            $article->image = $path;
            $article->save();
        endif;
        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Article $article
     * @return Response
     */
    public function destroy(Article $article)
    {
        //
        $article->categories()->detach();
        if (($article->image != null) && (file_exists(public_path() . '/storage/' . $article->image))):
            unlink(public_path('/storage/' . $article->image));
        endif;
        $article->delete();
        return redirect()->route('admin.article.index');
    }


}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container-fluid">

        @component('admin.components.breadcrumb')
            @slot('title') Создание новости @endslot
            @slot('parent') Главная @endslot
            @slot('active') Новости @endslot
        @endcomponent

        <hr/>

        <form class="form-horizontal" action="{{route('admin.article.store')}}" method="post"
              enctype="multipart/form-data">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.articles.partials.form')
            <input type="hidden" name="created_by" value="{{Auth::id()}}">
        </form>
    </div>

@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container-fluid">

        @component('admin.components.breadcrumb')
            @slot('title') Редактирование новости @endslot
            @slot('parent') Главная @endslot
            @slot('active') Новости @endslot
        @endcomponent

        <hr/>

        <form class="form-horizontal" action="{{route('admin.article.update', $article)}}" method="post"
              enctype="multipart/form-data">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            {{-- Form include --}}
            @include('admin.articles.partials.form')
            <input type="hidden" name="modified_by" value="{{Auth::id()}}">
        </form>
    </div>

@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container-fluid">

        @component('admin.components.breadcrumb')
            @slot('title') Список новостей @endslot
            @slot('parent') Главная @endslot
            @slot('active')  Новости @endslot
        @endcomponent

        <hr>
        <h4>Фильтры:</h4>
        <table class="table table-striped">
            <thead>
            <th>Поиск по названию</th>
            <th>Сортировка по категории</th>
            <th>Сортировка по публикации</th>

            </thead>
            <tbody>
            <td>
                <form class="form-inline my-2 my-md-0" action="{{route('admin.article.index')}}" method="get">
                    <input name="searching" class="form-control" type="text" placeholder="Введите запрос..."
                           aria-label="Search">
                    <button class="btn" type="submit"><i class="fa fa-search"></i></button>
                </form>
            </td>
            <td>
                <form class="form-inline my-2 my-md-0" action="{{route('admin.article.index')}}" method="get">
                    <select class="form-control" name="category_search">
                        <option value="0">-- Все категории --</option>

                        @forelse ($categories as $category)


                            <option value="{{$category->id ?? ""}}"
                            >
                                {{$category->title ?? ""}}
                            </option>

                        @empty
                        @endforelse
                    </select>
                    <button class="btn" type="submit"><i class="fa fa-search"></i></button>
                </form>
            </td>
            <td>
                <form class="form-inline my-2 my-md-0" action="{{route('admin.article.index')}}" method="get">
                    <select class="form-control" name="category_published">

                        <option value="0">Не опубликовано</option>
                        <option value="1">Опубликовано</option>

                    </select>
                    <button class="btn" type="submit"><i class="fa fa-search"></i></button>
                </form>
            </td>
            </tbody>
        </table>
        <hr>
        <a href="{{route('admin.article.create')}}" class="btn btn-primary pull-right"><i
                    class="fa fa-plus-square-o"></i> Создать новость</a>
        <br><br>

        <table class="table table-striped">
            <thead>
            <th>Наименование</th>
            <th>Публикация</th>
            <th>Изображение</th>
            <th>Категория</th>
            <th class="text-right">Действие</th>
            </thead>
            <tbody>
            @forelse ($articles as $article)
                <tr>
                    <td>{{$article->title}}</td>

                    <td>{{$article->published}}</td>
                    <td width="250"><img src="/storage/{{ $article->image ?? ''}}" alt=""></td>
                    <td>{{$article->categories()->pluck('title')->implode(', ')}}</td>
                    <td class="text-right">
                        <form onsubmit="if(confirm('Удалить?')){return true }else{return false}"
                              action="{{route('admin.article.destroy', $article)}}" method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            {{csrf_field()}}
                            <a class="btn btn-default" href="{{route('admin.article.edit', $article)}}"><i
                                        class="fa fa-edit"></i></a>
                            <button class="btn" type="submit"><i class="fa fa-trash-o"></i></button>
                        </form>


                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center"><h2>Данные отсутствуют</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <td colspan="5">
                <ul class="pagination pull-right">
                    {{$articles->links()}}
                </ul>
            </td>
            </tfoot>
        </table>
    </div>

@endsection